server:
  port: 8888
spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8
logging:
  level:
    org.springframework: debug
merryyou:
  security:
    oauth2:
      storeType: jwt #ou jwt
      jwtSigningKey: firstDecision
      clients[0]:
        clientId: firstDecision
        clientSecret: firstDecision
      clients[1]:
              clientId: firstDecision1
              clientSecret: firstDecision1
