auth-server: http://localhost:8888 Endereço do servidor SSO
server:
  port: 8889
security:
  oauth2:
    client:
      client-id: merryyou
      client-secret: merryyou
      user-authorization-uri: ${auth-server}/oauth/authorize #Endereço de solicitação de autenticação.
      access-token-uri: ${auth-server}/oauth/token #Endereço para solicitar o token
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key
      user-info-uri: ${auth-server}/user/me
      token-info-uri: ${auth-server}/oauth/check_token
logging:
  level:
    org.springframework: debug